---

- name: install unzip
  yum:
    name: unzip

- name: "mkdir {{ app_name }}"
  file:
    path: "{{ item }}/{{ app_name }}"
    owner: root
    group: root
    state: directory
  with_items:
    - /opt
    - /etc
    - /var/log
    - /var/run

- name: "copy /etc/tmpfiles.d/{{ app_name }}.conf"
  template:
    src: tmpfiles_d.conf
    dest: "/etc/tmpfiles.d/{{ app_name }}.conf"

- name: "copy /etc/systemd/system/{{ app_name }}"
  template:
    src: service-file.service
    dest: "/etc/systemd/system/{{ app_name }}.service"
    owner: root
    mode: 0644

- name: systemctl daemon reload
  systemd:
    name: "{{ app_name }}"
    daemon_reload: yes

- name: "copy {{ app_name }}-0.1.0-SNAPSHOT.zip"
  copy:
    src: "{{ app_name }}-0.1.0-SNAPSHOT.zip"
    dest: "/opt/{{ app_name }}/{{ app_name }}-0.1.0-SNAPSHOT.zip"

- name: delete old directory
  file:
    path: "/opt/{{ app_name }}/{{ app_name }}-0.1.0-SNAPSHOT"
    state: absent

- name: "unzip {{ app_name }}"
  unarchive:
    remote_src: yes
    src: "/opt/{{ app_name }}/{{ app_name }}-0.1.0-SNAPSHOT.zip"
    dest: "/opt/{{ app_name }}"

- name: copy application.conf
  template:
    src: application.conf
    dest: "/etc/{{ app_name }}/application.conf"
    owner: root
    group: root

- name: copy logback.xml
  template:
    src: logback.xml
    dest: "/etc/{{ app_name }}/logback.xml"
    owner: root
    group: root

- name: "{{ app_name }} stop"
  systemd:
    name: "{{ app_name }}"
    state: stopped

- name: "{{ app_name }} start"
  systemd:
    name: "{{ app_name }}"
    state: started
    enabled: yes
